/* This file is intended to cross the gap between @types/screeps and these typings */
type ResourceConstant = RESOURCE_CONSTANT;
type StoreDefinition = Store;
type ColorConstant = COLOR_CONSTANT;
type BodyPartConstant = BODYPART_CONSTANT;
type _ResourceConstantSansEnergy =
	| typeof RESOURCE_POWER
	| typeof RESOURCE_HYDROGEN
	| typeof RESOURCE_OXYGEN
	| typeof RESOURCE_UTRIUM
	| typeof RESOURCE_KEANIUM
	| typeof RESOURCE_LEMERGIUM
	| typeof RESOURCE_ZYNTHIUM
	| typeof RESOURCE_CATALYST
	| typeof RESOURCE_GHODIUM
	| typeof RESOURCE_HYDROXIDE
	| typeof RESOURCE_ZYNTHIUM_KEANITE
	| typeof RESOURCE_UTRIUM_LEMERGITE
	| typeof RESOURCE_UTRIUM_HYDRIDE
	| typeof RESOURCE_UTRIUM_OXIDE
	| typeof RESOURCE_KEANIUM_HYDRIDE
	| typeof RESOURCE_KEANIUM_OXIDE
	| typeof RESOURCE_LEMERGIUM_HYDRIDE
	| typeof RESOURCE_LEMERGIUM_OXIDE
	| typeof RESOURCE_ZYNTHIUM_HYDRIDE
	| typeof RESOURCE_ZYNTHIUM_OXIDE
	| typeof RESOURCE_GHODIUM_HYDRIDE
	| typeof RESOURCE_GHODIUM_OXIDE
	| typeof RESOURCE_UTRIUM_ACID
	| typeof RESOURCE_UTRIUM_ALKALIDE
	| typeof RESOURCE_KEANIUM_ACID
	| typeof RESOURCE_KEANIUM_ALKALIDE
	| typeof RESOURCE_LEMERGIUM_ACID
	| typeof RESOURCE_LEMERGIUM_ALKALIDE
	| typeof RESOURCE_ZYNTHIUM_ACID
	| typeof RESOURCE_ZYNTHIUM_ALKALIDE
	| typeof RESOURCE_GHODIUM_ACID
	| typeof RESOURCE_GHODIUM_ALKALIDE
	| typeof RESOURCE_CATALYZED_UTRIUM_ACID
	| typeof RESOURCE_CATALYZED_UTRIUM_ALKALIDE
	| typeof RESOURCE_CATALYZED_KEANIUM_ACID
	| typeof RESOURCE_CATALYZED_KEANIUM_ALKALIDE
	| typeof RESOURCE_CATALYZED_LEMERGIUM_ACID
	| typeof RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE
	| typeof RESOURCE_CATALYZED_ZYNTHIUM_ACID
	| typeof RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE
	| typeof RESOURCE_CATALYZED_GHODIUM_ACID
	| typeof RESOURCE_CATALYZED_GHODIUM_ALKALIDE;
type BodyPartDefinition = BodyPartInfo;
type SpawnOptions = Partial<SpawnOpts>;
type ScreepsReturnCode =
	| OK
	| ERR_NOT_OWNER
	| ERR_NO_PATH
	| ERR_BUSY
	| ERR_NAME_EXISTS
	| ERR_NOT_FOUND
	| ERR_NOT_ENOUGH_RESOURCES
	| ERR_NOT_ENOUGH_ENERGY
	| ERR_INVALID_TARGET
	| ERR_FULL
	| ERR_NOT_IN_RANGE
	| ERR_INVALID_ARGS
	| ERR_TIRED
	| ERR_NO_BODYPART
	| ERR_NOT_ENOUGH_EXTENSIONS
	| ERR_RCL_NOT_ENOUGH
	| ERR_GCL_NOT_ENOUGH;
type CreepActionReturnCode = OK | ERR_NOT_OWNER | ERR_BUSY | ERR_INVALID_TARGET | ERR_NOT_IN_RANGE | ERR_NO_BODYPART | ERR_TIRED;
type StructureConstant = STRUCTURE_CONSTANT;
type _HasRoomPosition = { pos: RoomPosition };

